/* Auto-generated by genmsg_cpp for file /home/ros/fuerte_workspace/sandbox/schunk_modular_robotics/schunk_sdh/msg/TactileSensor.msg */
#ifndef SCHUNK_SDH_MESSAGE_TACTILESENSOR_H
#define SCHUNK_SDH_MESSAGE_TACTILESENSOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "schunk_sdh/TactileMatrix.h"

namespace schunk_sdh
{
template <class ContainerAllocator>
struct TactileSensor_ {
  typedef TactileSensor_<ContainerAllocator> Type;

  TactileSensor_()
  : header()
  , tactile_matrix()
  {
  }

  TactileSensor_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , tactile_matrix(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::schunk_sdh::TactileMatrix_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::schunk_sdh::TactileMatrix_<ContainerAllocator> >::other >  _tactile_matrix_type;
  std::vector< ::schunk_sdh::TactileMatrix_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::schunk_sdh::TactileMatrix_<ContainerAllocator> >::other >  tactile_matrix;


  typedef boost::shared_ptr< ::schunk_sdh::TactileSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::schunk_sdh::TactileSensor_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TactileSensor
typedef  ::schunk_sdh::TactileSensor_<std::allocator<void> > TactileSensor;

typedef boost::shared_ptr< ::schunk_sdh::TactileSensor> TactileSensorPtr;
typedef boost::shared_ptr< ::schunk_sdh::TactileSensor const> TactileSensorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::schunk_sdh::TactileSensor_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::schunk_sdh::TactileSensor_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace schunk_sdh

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::schunk_sdh::TactileSensor_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::schunk_sdh::TactileSensor_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::schunk_sdh::TactileSensor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c6176a03c00cccf1b8efd3037de0d45d";
  }

  static const char* value(const  ::schunk_sdh::TactileSensor_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc6176a03c00cccf1ULL;
  static const uint64_t static_value2 = 0xb8efd3037de0d45dULL;
};

template<class ContainerAllocator>
struct DataType< ::schunk_sdh::TactileSensor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "schunk_sdh/TactileSensor";
  }

  static const char* value(const  ::schunk_sdh::TactileSensor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::schunk_sdh::TactileSensor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#tactile sensor data in 2D grid\n\
Header header\n\
schunk_sdh/TactileMatrix[] tactile_matrix\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: schunk_sdh/TactileMatrix\n\
uint32 matrix_id\n\
int16 cells_x\n\
int16 cells_y\n\
int16[] tactile_array\n\
\n\
";
  }

  static const char* value(const  ::schunk_sdh::TactileSensor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::schunk_sdh::TactileSensor_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::schunk_sdh::TactileSensor_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::schunk_sdh::TactileSensor_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.tactile_matrix);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TactileSensor_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::schunk_sdh::TactileSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::schunk_sdh::TactileSensor_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tactile_matrix[]" << std::endl;
    for (size_t i = 0; i < v.tactile_matrix.size(); ++i)
    {
      s << indent << "  tactile_matrix[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::schunk_sdh::TactileMatrix_<ContainerAllocator> >::stream(s, indent + "    ", v.tactile_matrix[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // SCHUNK_SDH_MESSAGE_TACTILESENSOR_H

